# Generated by Django 3.2.11 on 2022-03-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='name1',
        ),
    ]
