# Generated by Django 3.2.11 on 2022-03-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_auto_20220315_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='month',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(),
        ),
    ]
