# Generated by Django 3.2.11 on 2022-03-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_auto_20220315_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='month',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.IntegerField(),
        ),
    ]
